vich_uploader:
    db_driver: orm

    mappings:
        produit_image:
            uri_prefix: /uploads/produit
            upload_destination: '%kernel.project_dir%/public/uploads/produit'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
